name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Install Dependencies
      run: npm install --no-package-lock

    - name: Run Tests
      run: npm test
