# Smaller image, faster to download than the regular node:12 image.
image: node:12-alpine
# Before any job, add the vsce globally, and install our node_modules.
before_script:
  - yarn global add vsce
  - yarn

Deploy:
  script:
    - apk update
    - yarn package
    # publish our extension by passing in our $PAT token.
    - vsce publish -p $PAT

  only:
    - deploy